# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui-matrix.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(296, 533)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 241, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setText("")
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_3.setText("")
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 0, 2, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_10.setText("")
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout.addWidget(self.radioButton_10, 1, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setText("")
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_9.setText("")
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout.addWidget(self.radioButton_9, 1, 0, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_8.setText("")
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout.addWidget(self.radioButton_8, 0, 7, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_12.setText("")
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout.addWidget(self.radioButton_12, 1, 3, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_11.setText("")
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout.addWidget(self.radioButton_11, 1, 2, 1, 1)
        self.radioButton_13 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_13.setText("")
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName("radioButton_13")
        self.gridLayout.addWidget(self.radioButton_13, 1, 4, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_16.setText("")
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout.addWidget(self.radioButton_16, 1, 7, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_14.setText("")
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.gridLayout.addWidget(self.radioButton_14, 1, 5, 1, 1)
        self.radioButton_18 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_18.setText("")
        self.radioButton_18.setAutoExclusive(False)
        self.radioButton_18.setObjectName("radioButton_18")
        self.gridLayout.addWidget(self.radioButton_18, 2, 1, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_21.setText("")
        self.radioButton_21.setAutoExclusive(False)
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout.addWidget(self.radioButton_21, 2, 4, 1, 1)
        self.radioButton_15 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_15.setText("")
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout.addWidget(self.radioButton_15, 1, 6, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_17.setText("")
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout.addWidget(self.radioButton_17, 2, 0, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_19.setText("")
        self.radioButton_19.setAutoExclusive(False)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout.addWidget(self.radioButton_19, 2, 2, 1, 1)
        self.radioButton_20 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_20.setText("")
        self.radioButton_20.setAutoExclusive(False)
        self.radioButton_20.setObjectName("radioButton_20")
        self.gridLayout.addWidget(self.radioButton_20, 2, 3, 1, 1)
        self.radioButton_23 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_23.setText("")
        self.radioButton_23.setAutoExclusive(False)
        self.radioButton_23.setObjectName("radioButton_23")
        self.gridLayout.addWidget(self.radioButton_23, 2, 6, 1, 1)
        self.radioButton_28 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_28.setText("")
        self.radioButton_28.setAutoExclusive(False)
        self.radioButton_28.setObjectName("radioButton_28")
        self.gridLayout.addWidget(self.radioButton_28, 3, 3, 1, 1)
        self.radioButton_31 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_31.setText("")
        self.radioButton_31.setAutoExclusive(False)
        self.radioButton_31.setObjectName("radioButton_31")
        self.gridLayout.addWidget(self.radioButton_31, 3, 6, 1, 1)
        self.radioButton_26 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_26.setText("")
        self.radioButton_26.setAutoExclusive(False)
        self.radioButton_26.setObjectName("radioButton_26")
        self.gridLayout.addWidget(self.radioButton_26, 3, 1, 1, 1)
        self.radioButton_27 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_27.setText("")
        self.radioButton_27.setAutoExclusive(False)
        self.radioButton_27.setObjectName("radioButton_27")
        self.gridLayout.addWidget(self.radioButton_27, 3, 2, 1, 1)
        self.radioButton_22 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_22.setText("")
        self.radioButton_22.setAutoExclusive(False)
        self.radioButton_22.setObjectName("radioButton_22")
        self.gridLayout.addWidget(self.radioButton_22, 2, 5, 1, 1)
        self.radioButton_29 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_29.setText("")
        self.radioButton_29.setAutoExclusive(False)
        self.radioButton_29.setObjectName("radioButton_29")
        self.gridLayout.addWidget(self.radioButton_29, 3, 4, 1, 1)
        self.radioButton_30 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_30.setText("")
        self.radioButton_30.setAutoExclusive(False)
        self.radioButton_30.setObjectName("radioButton_30")
        self.gridLayout.addWidget(self.radioButton_30, 3, 5, 1, 1)
        self.radioButton_25 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_25.setText("")
        self.radioButton_25.setAutoExclusive(False)
        self.radioButton_25.setObjectName("radioButton_25")
        self.gridLayout.addWidget(self.radioButton_25, 3, 0, 1, 1)
        self.radioButton_24 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_24.setText("")
        self.radioButton_24.setAutoExclusive(False)
        self.radioButton_24.setObjectName("radioButton_24")
        self.gridLayout.addWidget(self.radioButton_24, 2, 7, 1, 1)
        self.radioButton_33 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_33.setText("")
        self.radioButton_33.setAutoExclusive(False)
        self.radioButton_33.setObjectName("radioButton_33")
        self.gridLayout.addWidget(self.radioButton_33, 4, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_5.setText("")
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 0, 4, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_4.setText("")
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 0, 3, 1, 1)
        self.radioButton_32 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_32.setText("")
        self.radioButton_32.setAutoExclusive(False)
        self.radioButton_32.setObjectName("radioButton_32")
        self.gridLayout.addWidget(self.radioButton_32, 3, 7, 1, 1)
        self.radioButton_34 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_34.setText("")
        self.radioButton_34.setAutoExclusive(False)
        self.radioButton_34.setObjectName("radioButton_34")
        self.gridLayout.addWidget(self.radioButton_34, 4, 1, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_7.setText("")
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout.addWidget(self.radioButton_7, 0, 6, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_6.setText("")
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout.addWidget(self.radioButton_6, 0, 5, 1, 1)
        self.radioButton_36 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_36.setText("")
        self.radioButton_36.setAutoExclusive(False)
        self.radioButton_36.setObjectName("radioButton_36")
        self.gridLayout.addWidget(self.radioButton_36, 4, 3, 1, 1)
        self.radioButton_35 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_35.setText("")
        self.radioButton_35.setAutoExclusive(False)
        self.radioButton_35.setObjectName("radioButton_35")
        self.gridLayout.addWidget(self.radioButton_35, 4, 2, 1, 1)
        self.radioButton_39 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_39.setText("")
        self.radioButton_39.setAutoExclusive(False)
        self.radioButton_39.setObjectName("radioButton_39")
        self.gridLayout.addWidget(self.radioButton_39, 4, 6, 1, 1)
        self.radioButton_40 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_40.setText("")
        self.radioButton_40.setAutoExclusive(False)
        self.radioButton_40.setObjectName("radioButton_40")
        self.gridLayout.addWidget(self.radioButton_40, 4, 7, 1, 1)
        self.radioButton_37 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_37.setText("")
        self.radioButton_37.setAutoExclusive(False)
        self.radioButton_37.setObjectName("radioButton_37")
        self.gridLayout.addWidget(self.radioButton_37, 4, 4, 1, 1)
        self.radioButton_38 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_38.setText("")
        self.radioButton_38.setAutoExclusive(False)
        self.radioButton_38.setObjectName("radioButton_38")
        self.gridLayout.addWidget(self.radioButton_38, 4, 5, 1, 1)
        self.radioButton_44 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_44.setText("")
        self.radioButton_44.setAutoExclusive(False)
        self.radioButton_44.setObjectName("radioButton_44")
        self.gridLayout.addWidget(self.radioButton_44, 5, 3, 1, 1)
        self.radioButton_41 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_41.setText("")
        self.radioButton_41.setAutoExclusive(False)
        self.radioButton_41.setObjectName("radioButton_41")
        self.gridLayout.addWidget(self.radioButton_41, 5, 0, 1, 1)
        self.radioButton_43 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_43.setText("")
        self.radioButton_43.setAutoExclusive(False)
        self.radioButton_43.setObjectName("radioButton_43")
        self.gridLayout.addWidget(self.radioButton_43, 5, 2, 1, 1)
        self.radioButton_42 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_42.setText("")
        self.radioButton_42.setAutoExclusive(False)
        self.radioButton_42.setObjectName("radioButton_42")
        self.gridLayout.addWidget(self.radioButton_42, 5, 1, 1, 1)
        self.radioButton_45 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_45.setText("")
        self.radioButton_45.setAutoExclusive(False)
        self.radioButton_45.setObjectName("radioButton_45")
        self.gridLayout.addWidget(self.radioButton_45, 5, 4, 1, 1)
        self.radioButton_46 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_46.setText("")
        self.radioButton_46.setAutoExclusive(False)
        self.radioButton_46.setObjectName("radioButton_46")
        self.gridLayout.addWidget(self.radioButton_46, 5, 5, 1, 1)
        self.radioButton_49 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_49.setText("")
        self.radioButton_49.setAutoExclusive(False)
        self.radioButton_49.setObjectName("radioButton_49")
        self.gridLayout.addWidget(self.radioButton_49, 6, 0, 1, 1)
        self.radioButton_47 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_47.setText("")
        self.radioButton_47.setAutoExclusive(False)
        self.radioButton_47.setObjectName("radioButton_47")
        self.gridLayout.addWidget(self.radioButton_47, 5, 6, 1, 1)
        self.radioButton_48 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_48.setText("")
        self.radioButton_48.setAutoExclusive(False)
        self.radioButton_48.setObjectName("radioButton_48")
        self.gridLayout.addWidget(self.radioButton_48, 5, 7, 1, 1)
        self.radioButton_51 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_51.setText("")
        self.radioButton_51.setAutoExclusive(False)
        self.radioButton_51.setObjectName("radioButton_51")
        self.gridLayout.addWidget(self.radioButton_51, 6, 2, 1, 1)
        self.radioButton_50 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_50.setText("")
        self.radioButton_50.setAutoExclusive(False)
        self.radioButton_50.setObjectName("radioButton_50")
        self.gridLayout.addWidget(self.radioButton_50, 6, 1, 1, 1)
        self.radioButton_55 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_55.setText("")
        self.radioButton_55.setAutoExclusive(False)
        self.radioButton_55.setObjectName("radioButton_55")
        self.gridLayout.addWidget(self.radioButton_55, 6, 6, 1, 1)
        self.radioButton_52 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_52.setText("")
        self.radioButton_52.setAutoExclusive(False)
        self.radioButton_52.setObjectName("radioButton_52")
        self.gridLayout.addWidget(self.radioButton_52, 6, 3, 1, 1)
        self.radioButton_53 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_53.setText("")
        self.radioButton_53.setAutoExclusive(False)
        self.radioButton_53.setObjectName("radioButton_53")
        self.gridLayout.addWidget(self.radioButton_53, 6, 4, 1, 1)
        self.radioButton_54 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_54.setText("")
        self.radioButton_54.setAutoExclusive(False)
        self.radioButton_54.setObjectName("radioButton_54")
        self.gridLayout.addWidget(self.radioButton_54, 6, 5, 1, 1)
        self.radioButton_56 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_56.setText("")
        self.radioButton_56.setAutoExclusive(False)
        self.radioButton_56.setObjectName("radioButton_56")
        self.gridLayout.addWidget(self.radioButton_56, 6, 7, 1, 1)
        self.radioButton_57 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_57.setText("")
        self.radioButton_57.setAutoExclusive(False)
        self.radioButton_57.setObjectName("radioButton_57")
        self.gridLayout.addWidget(self.radioButton_57, 7, 0, 1, 1)
        self.radioButton_58 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_58.setText("")
        self.radioButton_58.setAutoExclusive(False)
        self.radioButton_58.setObjectName("radioButton_58")
        self.gridLayout.addWidget(self.radioButton_58, 7, 1, 1, 1)
        self.radioButton_59 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_59.setText("")
        self.radioButton_59.setAutoExclusive(False)
        self.radioButton_59.setObjectName("radioButton_59")
        self.gridLayout.addWidget(self.radioButton_59, 7, 2, 1, 1)
        self.radioButton_60 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_60.setText("")
        self.radioButton_60.setAutoExclusive(False)
        self.radioButton_60.setObjectName("radioButton_60")
        self.gridLayout.addWidget(self.radioButton_60, 7, 3, 1, 1)
        self.radioButton_61 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_61.setText("")
        self.radioButton_61.setAutoExclusive(False)
        self.radioButton_61.setObjectName("radioButton_61")
        self.gridLayout.addWidget(self.radioButton_61, 7, 4, 1, 1)
        self.radioButton_62 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_62.setText("")
        self.radioButton_62.setAutoExclusive(False)
        self.radioButton_62.setObjectName("radioButton_62")
        self.gridLayout.addWidget(self.radioButton_62, 7, 5, 1, 1)
        self.radioButton_63 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_63.setText("")
        self.radioButton_63.setAutoExclusive(False)
        self.radioButton_63.setObjectName("radioButton_63")
        self.gridLayout.addWidget(self.radioButton_63, 7, 6, 1, 1)
        self.radioButton_64 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_64.setText("")
        self.radioButton_64.setAutoExclusive(False)
        self.radioButton_64.setObjectName("radioButton_64")
        self.gridLayout.addWidget(self.radioButton_64, 7, 7, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 310, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 370, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 430, 241, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.gridLayoutWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.gridLayoutWidget_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MAX7219 LED Matrix - Raspberry Pi"))
        self.pushButton.setText(_translate("Form", "Update matrix"))
        self.pushButton_2.setText(_translate("Form", "Generate matrix"))
        self.comboBox.setItemText(0, _translate("Form", "0"))
        self.comboBox.setItemText(1, _translate("Form", "90"))
        self.comboBox.setItemText(2, _translate("Form", "180"))
        self.comboBox.setItemText(3, _translate("Form", "270"))
        self.label.setText(_translate("Form", "Matrix orientation:"))
        self.label_2.setText(_translate("Form", "Output style:"))
        self.comboBox_2.setItemText(0, _translate("Form", "Numpy-style matrix"))
        self.comboBox_2.setItemText(1, _translate("Form", "Binary"))

import rsrc_rc
